services:
  backend:
    image: ghcr.io/${USER}/poke-atlas-backend:${BACKEND_IMAGE_TAG}
    ports: 
      - "8080:8080"
  
  frontend:
    image: ghcr.io/${USER}/poke-atlas-frontend:${FRONTEND_IMAGE_TAG}
    ports: 
      - "80:3000"