services:
  backend:
    image: ghcr.io/${USER}/poke-atlas-backend:${IMAGE_TAG}
    ports: 
      - "8080:8080"
  
  frontend:
    image: ghcr.io/${USER}/poke-atlas-frontend:${IMAGE_TAG}
    ports: 
      - "80:3001"